// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJLNY0Xf-YDAbyz6-wW0aMs0Hai0S5ry4',
    appId: '1:559694106928:web:8f342da738718520cc38f5',
    messagingSenderId: '559694106928',
    projectId: 'mid-term-ff345',
    authDomain: 'mid-term-ff345.firebaseapp.com',
    storageBucket: 'mid-term-ff345.appspot.com',
    measurementId: 'G-XYYJ5BT4C9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUicPDMtp9CHVAM_fAE4uvSs5jgeu42k8',
    appId: '1:559694106928:android:0f56e9e809a5ba2ecc38f5',
    messagingSenderId: '559694106928',
    projectId: 'mid-term-ff345',
    storageBucket: 'mid-term-ff345.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcW3BYiJi_z5k4qExKvSbLyKIwYoM_GyU',
    appId: '1:559694106928:ios:e13018a87fff0e6acc38f5',
    messagingSenderId: '559694106928',
    projectId: 'mid-term-ff345',
    storageBucket: 'mid-term-ff345.appspot.com',
    iosClientId: '559694106928-mjn1l55blm83pur610ks8ftavamttb35.apps.googleusercontent.com',
    iosBundleId: 'com.example.midterm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcW3BYiJi_z5k4qExKvSbLyKIwYoM_GyU',
    appId: '1:559694106928:ios:e13018a87fff0e6acc38f5',
    messagingSenderId: '559694106928',
    projectId: 'mid-term-ff345',
    storageBucket: 'mid-term-ff345.appspot.com',
    iosClientId: '559694106928-mjn1l55blm83pur610ks8ftavamttb35.apps.googleusercontent.com',
    iosBundleId: 'com.example.midterm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJLNY0Xf-YDAbyz6-wW0aMs0Hai0S5ry4',
    appId: '1:559694106928:web:b476615e34bd3627cc38f5',
    messagingSenderId: '559694106928',
    projectId: 'mid-term-ff345',
    authDomain: 'mid-term-ff345.firebaseapp.com',
    storageBucket: 'mid-term-ff345.appspot.com',
    measurementId: 'G-E5RCSZK721',
  );

}